### ISSUE TITLE
Support ZigZag encoding for signed ints?

### ISSUE THREAD

**Issue by reuzel** [chrisdickinson/varint#25]
Hi all,

Is there any chance of supporting [zigzag encoded](https://developers.google.com/protocol-buffers/docs/encoding?csw=1#types) signed integers? If not, I was wondering what would be the most performant way of doing the 'zigzag-calculation' given the loss of precision in the higher number ranges.

Joost

**Comment by chrisdickinson** [comment]
Ah, I have a [separate package](https://github.com/chrisdickinson/zigzag) for doing zigzag encoding!
