### ISSUE TITLE
4294967295 seems to be the max value

### ISSUE THREAD

**Issue by soldair** [chrisdickinson/varint#3]
Im a bytewise newb but i was wondering.. 

it's documented that varints can not be longer than eight bytes but this library can only encode up to int32 max at 5 bytes.

is this is just the limitation in js bitwise ops? and can it decode larger numbers from other varint implementations?

``` js

var varint = require('varint');

var a = varint.encode(1387325649589);// Date.now()
// [ 181, 229, 181, 24 ]

varint.decode(a);
// 51212981

```

**Comment by listenaddress** [comment]
Hey y'all, couple questions. I'm trying to encode Filecoin addresses with the ID protocol. These addresses can be up to 20 numbers long, i.e. 13389068808970846986...

I'm curious if y'all would have a strategy to recommend for tackling this?
Or if you've seen any work done to encode big(ger) numbers?
